---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-secret
  namespace: pihole-dns
spec:
  encryptedData:
    FTLCONF_webserver_api_password: AgCvW2jolrEG8w7yljQOJeY/cVOZQSrsxpWddkf+3/PpGpJfWzbt5DmJ0FQN9XHt22fUGgWSjrO1rX8xu3LpmV7lnETJ6Vou+w+5qsMQXjd5dYV22uBbpAoi+kpss7ZtdHFqnCMlncygCy8MtzMWU8iUijtpYwskuwUix6VUhBMBqm0BMQ04IUmNTxN97gCxwXKf47d78AiT8R8JkVbLHr+xlJ4igfYZPnmTtNY5DjKOl62lomfL1CaOk3NdELIkN2HkWoR6xdaoA4bYkNT8J6fUHbtkjuIQ95njXje4aMotKrzzUTcoCbLMTLzpnTk3wrqzB4UU+u4Japh0F5UUUxuju7ugQUKa0Zxmb5L06rv3BkpCtpfEg65ivWN7QjJo7tpHmLY5jE26+33PQPx2aRdU8N48ZNQyDbAtp/bugU7Wr8dvbyNsRmHfK3n3GFkviHOQNX7X8tBvj9AbjNYXJSkFnUpcWXiBWMhOTMXNnE6+HXiaa/lwxAex2lrsG7FKLZ/gSAQbVTXll1u8PQi8spx1HmitKiy/4UVcb2eCs0iPNhPyRLc1Kww6deQTPF5hu480GoHx8nUZqGPLbdJyGh9qLTa0vjHX6x0X4kDs10mIT2um3K7CoHVlrvhLWqWmdvjjBXPaN4pDMSxbInkXpjvXCj0Z6TZYaTfJt9eqaY/wPrCU5Y9vOeSihq7KwxtHeTLPwVU6S6j9pMJhTQ==
  template:
    metadata:
      name: pihole-secret
      namespace: pihole-dns
