---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-secret
  namespace: pihole-dns
spec:
  encryptedData:
    FTLCONF_webserver_api_password: AgAcNVCcygXthSDjLpC/xHVBjPxxlLL4NoPkKnPcFjmvumXkxUMEefHXskQ0o2ZjIXt1ROoSaV0zQYpq9OC4k1Ks+PpfPmVG8qxHMXbyDdHxIyU3ZSSFA/MufBHjHqQ4cVyZrQ1Q6eSXyUvfizkc1NFFuBwRPWeC4CL3kt4/X5bnMstQRLeNP8wvV6o2agaQKuseeVYwrD0uVDwhhr4z0vWmLeDM/f/2WPc/4byWIFKjtKAC4rgoYKkWzfBPQOLsBsAJ4ggIxlXqkByOXtL8/nI79UdoemEomKzShYW+5BQvM+MOpp87AHKA4rTIXktXEwQzt2eLaFyX1fn0fHV4cBCLtDZIefF0cWTQSe0xq0kZq3Qb4bN4r37BViDsxokfusj2+HKMacBEhlkq27XhPblU+Urd7DgWo9e/R7C2s1MlNegiaux4POM8KDRTnKixdi3kyWrHwOkXSE5eASZSwOFlJLT7q4RdVSuklY03I+lw5aR0BWngV1O5Tu2cg4P4HfIgUgX2cZm9B40vIslOw4nFVjLXgxKfHrYPHja0vIDC4+9waOl5oXyjUQCxOkakYSckeIx4byUxnFlp6jhjYyCk0u2qfq0k6cmEsH4gm24OHMgDTT2M1MiVIIM63fuXnKLVDdvhjthQsXC/WvNMs1guxg1o+iagDerlFt3tkhdRj/Tu2GDdHDlGL1GWFY+OFqibfhpBUGZTHaQiIQ==
  template:
    metadata:
      name: pihole-secret
      namespace: pihole-dns
