apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: mealie
  name: mealie
spec:
  ports:
    - name: "9925"
      port: 9925
      targetPort: 9000
  selector:
    io.kompose.service: mealie
