apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: immich-machine-learning
  name: immich-machine-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: immich-machine-learning
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yml
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: immich-machine-learning
    spec:
      containers:
        - image: ghcr.io/immich-app/immich-machine-learning:release
          name: immich-machine-learning
          volumeMounts:
            - mountPath: /cache
              name: model-cache
      restartPolicy: Always
      volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: model-cache
