apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-claim
  namespace: immich
spec:
  storageClassName: longhorn-ssd
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
