services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.16.0 # 
    container_name: mealie
    restart: always
    ports:
        - "9925:9000"
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - mealie-data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
      BASE_URL: https://192.168.0.12:9925

volumes:
  mealie-data:
